const accomSeeding = [
    {
        userId: 1,
        name: "The Sukosol Hotel",
        lat: "13.756982",
        lng: "100.532694",
        address: "477 Si Ayuthaya Rd, Thanon Phaya Thai, Ratchathewi, Bangkok 10400",
        province: "Bangkok",
        district: "Ratchathewi",
        type: "HOTEL",
        status: "ACTIVE",
        description: "A luxurious stay awaits you at The Sukosol Hotel with complimentary Wi-Fi, parking, and a state-of-the-art fitness center.",
    },
    {
        userId: 1,
        name: "Pullman Bangkok King Power",
        lat: "13.758408",
        lng: "100.537067",
        address: "8/2 Rangnam Rd, Thanon Phaya Thai, Ratchathewi, Bangkok 10400",
        province: "Bangkok",
        district: "Ratchathewi",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Experience top-notch amenities including free Wi-Fi, parking, and a beautiful swimming pool at Pullman Bangkok King Power.",
    },
    {
        userId: 1,
        name: "The Berkeley Hotel Pratunam",
        lat: "13.750840",
        lng: "100.541720",
        address: "559 Ratchaprarop Rd, Makkasan, Ratchathewi, Bangkok 10400",
        province: "Bangkok",
        district: "Ratchathewi",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Stay at The Berkeley Hotel Pratunam for luxurious accommodations, free Wi-Fi, and convenient access to shopping and dining.",
    },
    {
        userId: 1,
        name: "Amari Watergate Bangkok",
        lat: "13.751484",
        lng: "100.541662",
        address: "847 Phetchaburi Rd, Makkasan, Ratchathewi, Bangkok 10400",
        province: "Bangkok",
        district: "Ratchathewi",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Amari Watergate Bangkok offers premium facilities including a swimming pool, fitness center, and complimentary Wi-Fi.",
    },
    {
        userId: 1,
        name: "Novotel Bangkok Platinum Pratunam",
        lat: "13.748984",
        lng: "100.540070",
        address: "220 Petchaburi Rd, Ratchathewi, Bangkok 10400",
        province: "Bangkok",
        district: "Ratchathewi",
        type: "HOTEL",
        status: "ACTIVE",
        description:
            "Novotel Bangkok Platinum Pratunam provides guests with luxurious rooms, free Wi-Fi, and a central location near shopping districts.",
    },
    {
        userId: 1,
        name: "The Quarter Hualamphong by UHG",
        lat: "13.737263",
        lng: "100.516689",
        address: "23/34-35 Traimit Road, Talat Noi, Samphanthawong, Bangkok 10100",
        province: "Bangkok",
        district: "Samphanthawong",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Enjoy modern amenities and convenient access to public transportation at The Quarter Hualamphong by UHG.",
    },
    {
        userId: 1,
        name: "Mandarin Hotel Managed by Centre Point",
        lat: "13.730186",
        lng: "100.528470",
        address: "662 Rama IV Rd, Maha Phruttharam, Bang Rak, Bangkok 10500",
        province: "Bangkok",
        district: "Bang Rak",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Mandarin Hotel offers luxurious rooms, a swimming pool, and complimentary Wi-Fi, situated in the heart of Bangkok.",
    },
    {
        userId: 1,
        name: "Eastin Grand Hotel Sathorn Bangkok",
        lat: "13.719737",
        lng: "100.518024",
        address: "33/1 South Sathorn Rd, Yannawa, Sathorn, Bangkok 10120",
        province: "Bangkok",
        district: "Sathorn",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Eastin Grand Hotel Sathorn Bangkok features premium accommodations, free Wi-Fi, and a stunning infinity pool.",
    },
    {
        userId: 1,
        name: "Shangri-La Hotel, Bangkok",
        lat: "13.722002",
        lng: "100.514746",
        address: "89 Soi Wat Suan Plu, New Road, Bangrak, Bangkok 10500",
        province: "Bangkok",
        district: "Bang Rak",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Stay in luxury at Shangri-La Hotel, Bangkok with world-class facilities, complimentary Wi-Fi, and breathtaking river views.",
    },
    {
        userId: 1,
        name: "Lebua at State Tower",
        lat: "13.721032",
        lng: "100.514062",
        address: "1055 Silom Rd, Silom, Bang Rak, Bangkok 10500",
        province: "Bangkok",
        district: "Bang Rak",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Lebua at State Tower offers exceptional service, luxurious rooms, and a stunning rooftop bar with panoramic views of Bangkok.",
    },
    {
        userId: 1,
        name: "The Siam Hotel",
        lat: "13.761400",
        lng: "100.509300",
        address: "3/2 Thanon Khao, Vachirapayabal, Dusit, Bangkok 10300",
        province: "Bangkok",
        district: "Dusit",
        type: "HOTEL",
        status: "ACTIVE",
        description: "The Siam Hotel offers an elegant retreat with luxurious suites, free Wi-Fi, and a riverside infinity pool.",
    },
    {
        userId: 1,
        name: "Chatrium Hotel Riverside Bangkok",
        lat: "13.706770",
        lng: "100.510499",
        address: "28 Charoen Krung Rd, Wat Phraya Krai, Bang Kho Laem, Bangkok 10120",
        province: "Bangkok",
        district: "Bang Kho Laem",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Chatrium Hotel Riverside Bangkok provides spacious rooms with river views, free Wi-Fi, and a luxurious swimming pool.",
    },
    {
        userId: 1,
        name: "Millennium Hilton Bangkok",
        lat: "13.726262",
        lng: "100.509593",
        address: "123 Charoennakorn Rd, Khlong Ton Sai, Khlong San, Bangkok 10600",
        province: "Bangkok",
        district: "Khlong San",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Millennium Hilton Bangkok offers elegant rooms, free Wi-Fi, and an infinity pool with panoramic views of the city.",
    },
    {
        userId: 1,
        name: "AVANI Riverside Bangkok Hotel",
        lat: "13.701800",
        lng: "100.507222",
        address: "257 Charoennakorn Rd, Thon Buri, Bangkok 10600",
        province: "Bangkok",
        district: "Thon Buri",
        type: "HOTEL",
        status: "ACTIVE",
        description: "AVANI Riverside Bangkok Hotel offers modern accommodations with stunning river views, free Wi-Fi, and a rooftop infinity pool.",
    },
    {
        userId: 1,
        name: "Bangkok Marriott Hotel The Surawongse",
        lat: "13.725051",
        lng: "100.525932",
        address: "262 Surawong Rd, Si Phraya, Bang Rak, Bangkok 10500",
        province: "Bangkok",
        district: "Bang Rak",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Bangkok Marriott Hotel The Surawongse provides luxurious rooms, free Wi-Fi, and a rooftop infinity pool with city views.",
    },
    {
        userId: 2,
        name: "Pathumwan Princess Hotel",
        lat: "13.746372",
        lng: "100.529728",
        address: "444 MBK Center, Phayathai Rd, Wang Mai, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Pathumwan Princess Hotel offers luxurious accommodations, free Wi-Fi, and a beautiful rooftop pool in the heart of Bangkok.",
    },
    {
        userId: 2,
        name: "Siam Kempinski Hotel Bangkok",
        lat: "13.746665",
        lng: "100.534456",
        address: "991/9 Rama I Rd, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Siam Kempinski Hotel Bangkok features elegant rooms, free Wi-Fi, and multiple swimming pools in a lush garden setting.",
    },
    {
        userId: 2,
        name: "Centara Grand at CentralWorld",
        lat: "13.746056",
        lng: "100.539306",
        address: "999/99 Rama I Rd, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Centara Grand at CentralWorld offers luxurious accommodations, free Wi-Fi, and a stunning rooftop bar with panoramic views.",
    },
    {
        userId: 2,
        name: "InterContinental Bangkok",
        lat: "13.744696",
        lng: "100.540410",
        address: "973 Ploenchit Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "InterContinental Bangkok features elegant rooms, free Wi-Fi, and a rooftop pool with city views in a prime location.",
    },
    {
        userId: 2,
        name: "Anantara Siam Bangkok Hotel",
        lat: "13.742700",
        lng: "100.542700",
        address: "155 Ratchadamri Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description:
            "Anantara Siam Bangkok Hotel offers luxurious accommodations, free Wi-Fi, and a beautiful outdoor pool in a lush garden setting.",
    },
    {
        userId: 2,
        name: "Renaissance Bangkok Ratchaprasong Hotel",
        lat: "13.743332",
        lng: "100.541153",
        address: "518/8 Ploenchit Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description:
            "Renaissance Bangkok Ratchaprasong Hotel features modern accommodations, free Wi-Fi, and a stunning rooftop pool with city views.",
    },
    {
        userId: 2,
        name: "Grand Hyatt Erawan Bangkok",
        lat: "13.744146",
        lng: "100.540680",
        address: "494 Rajdamri Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Grand Hyatt Erawan Bangkok offers luxurious accommodations, free Wi-Fi, and a beautiful rooftop pool in a prime location.",
    },
    {
        userId: 2,
        name: "The St. Regis Bangkok",
        lat: "13.740917",
        lng: "100.542039",
        address: "159 Rajadamri Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "The St. Regis Bangkok features elegant rooms, free Wi-Fi, and a stunning rooftop pool with panoramic views of the city.",
    },
    {
        userId: 2,
        name: "Banyan Tree Bangkok",
        lat: "13.723512",
        lng: "100.539410",
        address: "21/100 South Sathon Rd, Sathon, Bangkok 10120",
        province: "Bangkok",
        district: "Sathon",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Banyan Tree Bangkok offers luxurious accommodations, free Wi-Fi, and a stunning rooftop bar with panoramic views of the city.",
    },
    {
        userId: 2,
        name: "SO/ Bangkok",
        lat: "13.728408",
        lng: "100.541255",
        address: "2 North Sathorn Rd, Bang Rak, Bangkok 10500",
        province: "Bangkok",
        district: "Bang Rak",
        type: "HOTEL",
        status: "ACTIVE",
        description: "SO/ Bangkok features modern accommodations, free Wi-Fi, and a beautiful rooftop pool with city views.",
    },
    {
        userId: 2,
        name: "The Okura Prestige Bangkok",
        lat: "13.742506",
        lng: "100.548333",
        address: "Park Venture Ecoplex, 57 Wireless Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "The Okura Prestige Bangkok offers luxurious accommodations, free Wi-Fi, and a stunning infinity pool with panoramic views.",
    },
    {
        userId: 2,
        name: "Park Hyatt Bangkok",
        lat: "13.743667",
        lng: "100.548287",
        address: "Central Embassy, 88 Wireless Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Park Hyatt Bangkok features elegant rooms, free Wi-Fi, and a beautiful infinity pool with city views.",
    },
    {
        userId: 2,
        name: "Hotel Muse Bangkok Langsuan",
        lat: "13.740328",
        lng: "100.543944",
        address: "55/555 Langsuan Rd, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Hotel Muse Bangkok Langsuan offers stylish accommodations, free Wi-Fi, and a rooftop bar with panoramic city views.",
    },
    {
        userId: 2,
        name: "Sindhorn Kempinski Hotel Bangkok",
        lat: "13.740830",
        lng: "100.548527",
        address: "80 Soi Tonson, Lumphini, Pathum Wan, Bangkok 10330",
        province: "Bangkok",
        district: "Pathum Wan",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Sindhorn Kempinski Hotel Bangkok features luxurious rooms, free Wi-Fi, and a beautiful outdoor pool.",
    },
    {
        userId: 2,
        name: "JW Marriott Hotel Bangkok",
        lat: "13.741789",
        lng: "100.551674",
        address: "4 Sukhumvit Rd, Khlong Toei, Bangkok 10110",
        province: "Bangkok",
        district: "Khlong Toei",
        type: "HOTEL",
        status: "ACTIVE",
        description: "JW Marriott Hotel Bangkok offers elegant accommodations, free Wi-Fi, and a stunning rooftop pool with city views.",
    },
    {
        userId: 3,
        name: "Hotel 3-1",
        lat: "13.752132",
        lng: "100.532410",
        address: "Address for Hotel 3-1",
        province: "Bangkok",
        district: "District for Hotel 3-1",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-1. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-2",
        lat: "13.753234",
        lng: "100.533124",
        address: "Address for Hotel 3-2",
        province: "Bangkok",
        district: "District for Hotel 3-2",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-2. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-3",
        lat: "13.754345",
        lng: "100.534678",
        address: "Address for Hotel 3-3",
        province: "Bangkok",
        district: "District for Hotel 3-3",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-3. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-4",
        lat: "13.755456",
        lng: "100.535789",
        address: "Address for Hotel 3-4",
        province: "Bangkok",
        district: "District for Hotel 3-4",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-4. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-5",
        lat: "13.756567",
        lng: "100.536890",
        address: "Address for Hotel 3-5",
        province: "Bangkok",
        district: "District for Hotel 3-5",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-5. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-6",
        lat: "13.757678",
        lng: "100.537901",
        address: "Address for Hotel 3-6",
        province: "Bangkok",
        district: "District for Hotel 3-6",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-6. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-7",
        lat: "13.758789",
        lng: "100.538912",
        address: "Address for Hotel 3-7",
        province: "Bangkok",
        district: "District for Hotel 3-7",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-7. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-8",
        lat: "13.759890",
        lng: "100.539923",
        address: "Address for Hotel 3-8",
        province: "Bangkok",
        district: "District for Hotel 3-8",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-8. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-9",
        lat: "13.760901",
        lng: "100.540934",
        address: "Address for Hotel 3-9",
        province: "Bangkok",
        district: "District for Hotel 3-9",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-9. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-10",
        lat: "13.761012",
        lng: "100.541945",
        address: "Address for Hotel 3-10",
        province: "Bangkok",
        district: "District for Hotel 3-10",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-10. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-11",
        lat: "13.762123",
        lng: "100.542956",
        address: "Address for Hotel 3-11",
        province: "Bangkok",
        district: "District for Hotel 3-11",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-11. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-12",
        lat: "13.763234",
        lng: "100.543967",
        address: "Address for Hotel 3-12",
        province: "Bangkok",
        district: "District for Hotel 3-12",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-12. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-13",
        lat: "13.764345",
        lng: "100.544978",
        address: "Address for Hotel 3-13",
        province: "Bangkok",
        district: "District for Hotel 3-13",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-13. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-14",
        lat: "13.765456",
        lng: "100.545989",
        address: "Address for Hotel 3-14",
        province: "Bangkok",
        district: "District for Hotel 3-14",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-14. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 3,
        name: "Hotel 3-15",
        lat: "13.766567",
        lng: "100.546990",
        address: "Address for Hotel 3-15",
        province: "Bangkok",
        district: "District for Hotel 3-15",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 3-15. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-1",
        lat: "13.752132",
        lng: "100.532410",
        address: "Address for Hotel 4-1",
        province: "Bangkok",
        district: "District for Hotel 4-1",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-1. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-2",
        lat: "13.753234",
        lng: "100.533124",
        address: "Address for Hotel 4-2",
        province: "Bangkok",
        district: "District for Hotel 4-2",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-2. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-3",
        lat: "13.754345",
        lng: "100.534678",
        address: "Address for Hotel 4-3",
        province: "Bangkok",
        district: "District for Hotel 4-3",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-3. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-4",
        lat: "13.755456",
        lng: "100.535789",
        address: "Address for Hotel 4-4",
        province: "Bangkok",
        district: "District for Hotel 4-4",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-4. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-5",
        lat: "13.756567",
        lng: "100.536890",
        address: "Address for Hotel 4-5",
        province: "Bangkok",
        district: "District for Hotel 4-5",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-5. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-6",
        lat: "13.757678",
        lng: "100.537901",
        address: "Address for Hotel 4-6",
        province: "Bangkok",
        district: "District for Hotel 4-6",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-6. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-7",
        lat: "13.758789",
        lng: "100.538912",
        address: "Address for Hotel 4-7",
        province: "Bangkok",
        district: "District for Hotel 4-7",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-7. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-8",
        lat: "13.759890",
        lng: "100.539923",
        address: "Address for Hotel 4-8",
        province: "Bangkok",
        district: "District for Hotel 4-8",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-8. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-9",
        lat: "13.760901",
        lng: "100.540934",
        address: "Address for Hotel 4-9",
        province: "Bangkok",
        district: "District for Hotel 4-9",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-9. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-10",
        lat: "13.761012",
        lng: "100.541945",
        address: "Address for Hotel 4-10",
        province: "Bangkok",
        district: "District for Hotel 4-10",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-10. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-11",
        lat: "13.762123",
        lng: "100.542956",
        address: "Address for Hotel 4-11",
        province: "Bangkok",
        district: "District for Hotel 4-11",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-11. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-12",
        lat: "13.763234",
        lng: "100.543967",
        address: "Address for Hotel 4-12",
        province: "Bangkok",
        district: "District for Hotel 4-12",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-12. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-13",
        lat: "13.764345",
        lng: "100.544978",
        address: "Address for Hotel 4-13",
        province: "Bangkok",
        district: "District for Hotel 4-13",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-13. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-14",
        lat: "13.765456",
        lng: "100.545989",
        address: "Address for Hotel 4-14",
        province: "Bangkok",
        district: "District for Hotel 4-14",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-14. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
    {
        userId: 4,
        name: "Hotel 4-15",
        lat: "13.766567",
        lng: "100.546990",
        address: "Address for Hotel 4-15",
        province: "Bangkok",
        district: "District for Hotel 4-15",
        type: "HOTEL",
        status: "ACTIVE",
        description: "Description for Hotel 4-15. Enjoy luxurious amenities including free Wi-Fi and parking.",
    },
]

function checkAndModifyDuplicates(hotels) {
    const latLngSet = new Set(); // Set to store unique lat-lng combinations

    hotels.forEach(hotel => {
        let { lat, lng } = hotel;
        const originalLat = lat;
        const originalLng = lng;

        // Generate new lat and lng until unique combination is found
        while (latLngSet.has(`${lat}-${lng}`)) {
            lat = parseFloat(originalLat) + (Math.random() * 0.02 - 0.01); // Adjust range as needed
            lng = parseFloat(originalLng) + (Math.random() * 0.02 - 0.01); // Adjust range as needed
        }

        // Update the hotel object with modified lat and lng
        hotel.lat = lat.toString();
        hotel.lng = lng.toString();

        // Add the new lat-lng combination to the set
        latLngSet.add(`${hotel.lat}-${hotel.lng}`);
    });
}
checkAndModifyDuplicates(accomSeeding)
console.log(accomSeeding)